# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4029f4130c492c17cd0af42f5a1ba1905f3b9ebb8e213cf4558b2afbf68dee9144ac67e873b5d18ebb482e2dc3986e3dff185c1b00d20d9154b616b60d658541

test:
  secret_key_base: 56bc6fc4cb0d2824036000165952e027c909f13be4cf9063862e991b6ba53b8f83ca24285e2a958fe58708bcc3178e5ba8ffc165d4a9558825a0b38a291cf36f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
